SET DATABASE UNIQUE NAME HSQLDB713636DAC1
SET DATABASE GC 0
SET DATABASE DEFAULT RESULT MEMORY ROWS 0
SET DATABASE EVENT LOG LEVEL 0
SET DATABASE TRANSACTION CONTROL LOCKS
SET DATABASE DEFAULT ISOLATION LEVEL READ COMMITTED
SET DATABASE TRANSACTION ROLLBACK ON CONFLICT TRUE
SET DATABASE TEXT TABLE DEFAULTS ''
SET DATABASE SQL NAMES FALSE
SET DATABASE SQL REFERENCES FALSE
SET DATABASE SQL SIZE TRUE
SET DATABASE SQL TYPES FALSE
SET DATABASE SQL TDC DELETE TRUE
SET DATABASE SQL TDC UPDATE TRUE
SET DATABASE SQL CONCAT NULLS TRUE
SET DATABASE SQL UNIQUE NULLS TRUE
SET DATABASE SQL CONVERT TRUNCATE TRUE
SET DATABASE SQL AVG SCALE 0
SET DATABASE SQL DOUBLE NAN TRUE
SET FILES WRITE DELAY 500 MILLIS
SET FILES BACKUP INCREMENT TRUE
SET FILES CACHE SIZE 10000
SET FILES CACHE ROWS 50000
SET FILES SCALE 32
SET FILES LOB SCALE 32
SET FILES DEFRAG 0
SET FILES NIO TRUE
SET FILES NIO SIZE 256
SET FILES LOG TRUE
SET FILES LOG SIZE 50
CREATE USER SA PASSWORD DIGEST 'd41d8cd98f00b204e9800998ecf8427e'
ALTER USER SA SET LOCAL TRUE
CREATE SCHEMA PUBLIC AUTHORIZATION DBA
SET SCHEMA PUBLIC
CREATE MEMORY TABLE PUBLIC.USER(ID BIGINT NOT NULL PRIMARY KEY,EMAIL VARCHAR(255),FIRST_NAME VARCHAR(255),IS_ACTIVE BOOLEAN,LAST_NAME VARCHAR(255),PASSWORD VARCHAR(255))
CREATE MEMORY TABLE PUBLIC.CARD(ID BIGINT NOT NULL PRIMARY KEY,IMAGE_URL VARCHAR(255),NAME VARCHAR(255),TYPE VARCHAR(255),VARIANT VARCHAR(255))
ALTER SEQUENCE SYSTEM_LOBS.LOB_ID RESTART WITH 1
SET DATABASE DEFAULT INITIAL SCHEMA PUBLIC
GRANT USAGE ON DOMAIN INFORMATION_SCHEMA.SQL_IDENTIFIER TO PUBLIC
GRANT USAGE ON DOMAIN INFORMATION_SCHEMA.YES_OR_NO TO PUBLIC
GRANT USAGE ON DOMAIN INFORMATION_SCHEMA.TIME_STAMP TO PUBLIC
GRANT USAGE ON DOMAIN INFORMATION_SCHEMA.CARDINAL_NUMBER TO PUBLIC
GRANT USAGE ON DOMAIN INFORMATION_SCHEMA.CHARACTER_DATA TO PUBLIC
GRANT DBA TO SA
SET SCHEMA SYSTEM_LOBS
INSERT INTO BLOCKS VALUES(0,2147483647,0)
SET SCHEMA PUBLIC
INSERT INTO USER VALUES(1,'khalil.stessens@ing.austral.edu.ar','Khalil',TRUE,'Stessens','caos123')
INSERT INTO USER VALUES(2,'kuharokun@gmail.com','Khalil',TRUE,'Stessens','123123123')
INSERT INTO CARD VALUES(1,'https://assets.pokemon.com/assets/cms2/img/cards/web/XY12/XY12_EN_3.png','Caterpie','Grass','Basic')
INSERT INTO CARD VALUES(2,'https://assets.pokemon.com/assets/cms2/img/cards/web/XY12/XY12_EN_4.png','Metapod','Grass','Stage 1')
INSERT INTO CARD VALUES(3,'https://assets.pokemon.com/assets/cms2/img/cards/web/XY12/XY12_EN_5.png','Weedle','Grass','Basic')
INSERT INTO CARD VALUES(4,'https://assets.pokemon.com/assets/cms2/img/cards/web/XY12/XY12_EN_6.png','Kakuna','Grass','Stage 1')
INSERT INTO CARD VALUES(5,'https://assets.pokemon.com/assets/cms2/img/cards/web/XY12/XY12_EN_7.png','Beedrill','Grass','Stage 2')
INSERT INTO CARD VALUES(6,'https://assets.pokemon.com/assets/cms2/img/cards/web/XY12/XY12_EN_8.png','Tangela','Grass','Basic')
INSERT INTO CARD VALUES(7,'https://assets.pokemon.com/assets/cms2/img/cards/web/XY12/XY12_EN_9.png','Charmander','Fire','Basic')
INSERT INTO CARD VALUES(8,'https://assets.pokemon.com/assets/cms2/img/cards/web/XY12/XY12_EN_10.png','Charmeleon','Fire','Stage 1')
INSERT INTO CARD VALUES(9,'https://assets.pokemon.com/assets/cms2/img/cards/web/XY12/XY12_EN_11.png','Charizard','Fire','Stage 2')
INSERT INTO CARD VALUES(10,'https://assets.pokemon.com/assets/cms2/img/cards/web/XY12/XY12_EN_12.png','Charizard','Fire','Basic EX')
INSERT INTO CARD VALUES(11,'https://assets.pokemon.com/assets/cms2/img/cards/web/XY12/XY12_EN_13.png','M-Charizard','Fire','Stage 1 EX')
INSERT INTO CARD VALUES(12,'https://assets.pokemon.com/assets/cms2/img/cards/web/XY12/XY12_EN_14.png','Vulpix','Fire','Basic')
INSERT INTO CARD VALUES(13,'https://assets.pokemon.com/assets/cms2/img/cards/web/XY12/XY12_EN_15.png','Ninetales','Fire','Stage 1')
INSERT INTO CARD VALUES(14,'https://assets.pokemon.com/assets/cms2/img/cards/web/XY12/XY12_EN_16.png','Ninetales','Fire','BREAK')
INSERT INTO CARD VALUES(15,'https://assets.pokemon.com/assets/cms2/img/cards/web/XY12/XY12_EN_17.png','Growlithe','Fire','Basic')
INSERT INTO CARD VALUES(16,'https://assets.pokemon.com/assets/cms2/img/cards/web/XY12/XY12_EN_18.png','Arcanine','Fire','Stage 1')
INSERT INTO CARD VALUES(17,'https://assets.pokemon.com/assets/cms2/img/cards/web/XY12/XY12_EN_19.png','Ponyta','Fire','Basic')
INSERT INTO CARD VALUES(18,'https://assets.pokemon.com/assets/cms2/img/cards/web/XY12/XY12_EN_20.png','Magmar','Fire','Basic')
INSERT INTO CARD VALUES(19,'https://assets.pokemon.com/assets/cms2/img/cards/web/XY12/XY12_EN_1.png','Venusaur','Grass','Basic EX')
INSERT INTO CARD VALUES(20,'https://assets.pokemon.com/assets/cms2/img/cards/web/XY12/XY12_EN_2.png','M-Venusaur','Grass','Stage 1 EX')
INSERT INTO CARD VALUES(21,'https://assets.pokemon.com/assets/cms2/img/cards/web/XY12/XY12_EN_21.png','Blastoise','Water','Basic EX')
INSERT INTO CARD VALUES(22,'https://assets.pokemon.com/assets/cms2/img/cards/web/XY12/XY12_EN_22.png','M-Blastoise','Water','Stage 1 EX')
INSERT INTO CARD VALUES(23,'https://assets.pokemon.com/assets/cms2/img/cards/web/XY12/XY12_EN_23.png','Poliwag','Water','Basic')
INSERT INTO CARD VALUES(24,'https://assets.pokemon.com/assets/cms2/img/cards/web/XY12/XY12_EN_24.png','Poliwhirl','Water','Stage 1')
